In [35]:
import numpy as np

In [36]:
nt = 3
nx = 4
ny = 5
nz = 6
t0, t1 = 0, 1
x0, x1 = 0, 1
y0, y1 = 0, 1
z0, z1 = 0, 1
t = np.linspace(t0, t1, nt)
x = np.linspace(x0, x1, nx)
y = np.linspace(y0, y1, ny)
z = np.linspace(z0, z1, nz)

In [37]:
# 1 dimension
T = np.copy(t)
D = np.copy(T)
print(D)

[0.  0.5 1. ]


In [38]:
# 2 dimension
T = np.repeat(t, nx)
X = np.tile(x, nt)
D = np.vstack([T, X]).T
print(D)

[[0.         0.        ]
 [0.         0.33333333]
 [0.         0.66666667]
 [0.         1.        ]
 [0.5        0.        ]
 [0.5        0.33333333]
 [0.5        0.66666667]
 [0.5        1.        ]
 [1.         0.        ]
 [1.         0.33333333]
 [1.         0.66666667]
 [1.         1.        ]]


In [39]:
# 3 dimension
T = np.repeat(t, nx*ny)
X = np.tile(np.repeat(x, ny), nt)
Y = np.tile(y, nt*nx)
D = np.vstack([T, X, Y]).T
print(D)

[[0.         0.         0.        ]
 [0.         0.         0.25      ]
 [0.         0.         0.5       ]
 [0.         0.         0.75      ]
 [0.         0.         1.        ]
 [0.         0.33333333 0.        ]
 [0.         0.33333333 0.25      ]
 [0.         0.33333333 0.5       ]
 [0.         0.33333333 0.75      ]
 [0.         0.33333333 1.        ]
 [0.         0.66666667 0.        ]
 [0.         0.66666667 0.25      ]
 [0.         0.66666667 0.5       ]
 [0.         0.66666667 0.75      ]
 [0.         0.66666667 1.        ]
 [0.         1.         0.        ]
 [0.         1.         0.25      ]
 [0.         1.         0.5       ]
 [0.         1.         0.75      ]
 [0.         1.         1.        ]
 [0.5        0.         0.        ]
 [0.5        0.         0.25      ]
 [0.5        0.         0.5       ]
 [0.5        0.         0.75      ]
 [0.5        0.         1.        ]
 [0.5        0.33333333 0.        ]
 [0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.5 

In [40]:
# 4 dimension
T = np.repeat(t, nx*ny*nz)
X = np.tile(np.repeat(x, ny*nz), nt)
Y = np.tile(np.repeat(y, nz), nt*nx)
Z = np.tile(z, nt*nx*ny)
D = np.vstack([T, X, Y, Z]).T
print(D)

[[0.  0.  0.  0. ]
 [0.  0.  0.  0.2]
 [0.  0.  0.  0.4]
 ...
 [1.  1.  1.  0.6]
 [1.  1.  1.  0.8]
 [1.  1.  1.  1. ]]


In [41]:
n_train = np.prod([nt, nx, ny, nz])
print(n_train)

360


In [42]:
len(D)

360

In [43]:
n = [3, 4, 5, 6]
b = [
    [0, 1],
    [0, 1],
    [0, 1],
    [0, 1],
]
n_dim = len(n)
n_train = np.prod(n)
print(n_dim, n_train)

4 360


In [44]:
x = []
for i in range(n_dim):
    x.append(np.linspace(b[i][0], b[i][1], n[i]))

In [60]:
grid = []
# grid.append(np.repeat(x[0], np.prod(n[1:])))
# for i in range(0, n_dim - 1):
for i in range(n_dim):
    grid.append(
      np.tile(
        np.repeat(x[i], np.prod(n[i + 1:])),
        np.prod(n[:i])
      )
    )
# grid.append(np.tile(x[-1], np.prod(n[:-1])))
D2 = np.vstack(grid).T

In [61]:
D.shape, D2.shape

((360, 4), (360, 4))

In [62]:
for p in D == D2:
    for v in p:
        if not v:
            print("FAIL")

In [64]:
D[179]

array([0.5       , 0.33333333, 1.        , 1.        ])